### PR TITLE
fix: banner and tracking

### LINKED ISSUE #849: track click through on announcement modal

### PR DESCRIPTION
**Pull request by Oxiang**
## Problem

IE Banner does not follow the vertical scroll
No tracking implemented for announcement modal

Closes #849 

## Solution

change the window.scrollY to window.pageYoffset as scrollY is incompatible with IE
change masthead's position to absolute as it does not disappear on scroll in IE
send GA event when announcement modal's button is clicked

## After Screenshots
IE top view
ie_top

IE bottom view after scrolling
ie_buttom

### CODE REVIEW

File: src/client/components/UserPage/AnnouncementModal/index.tsx [hunk 1]
```diff
@@ -229,6 +230,7 @@ export default function AnnouncementModal() {
             size="large"
             variant="text"
             className={classes.learnMoreButton}
+            onClick={()=> {GAEvent('Announcement Page', 'redirected to GoDirectory')}}
```
Comment (LoneRifle) [inline src/client/components/UserPage/AnnouncementModal/index.tsx:233]: Why the hardcoded reference to GoDirectory? the announcement modal is meant for more than that

**Review by LoneRifle — CHANGES_REQUESTED** [review]

File: src/client/components/UserPage/AnnouncementModal/index.tsx (hunk 1 above)
Comment (Oxiang) [reply src/client/components/UserPage/AnnouncementModal/index.tsx:233]: In the future when we change the subject of the announcement modal, we will change the event sent as well. So having the reference to godirectory will let us know in the google analytics dashboard that those existing clicks were referring to godirectory

Comment (LoneRifle) [reply src/client/components/UserPage/AnnouncementModal/index.tsx:233]: but do you really want to change the codebase every time an announcement has been made?

File: src/client/components/BaseLayout/Masthead.tsx [hunk 2]
```diff
@@ -11,6 +15,14 @@ const useStyles = makeStyles(() =>
...
       fontSize: '14px',
     },
+    mastheadsticky: {
+      zIndex: 2,
+      position: 'absolute',
+      backgroundColor: '#f0f0f0',
+      height: 'auto',
+      padding: '4px 0',
+      fontSize: '14px',
+    },
```
Comment (yong-jie) [inline src/client/components/BaseLayout/Masthead.tsx:25]: my observation here is that the only reason we had to declare this is to have a different `position` value. In this kind of situations, MUI allows us to specify props into the styles object to produce different classes. [Check this out](https://material-ui.com/styles/basics/#adapting-based-on-props)

I copied some examples in the web for reference

```javascript
const useStyles = makeStyles<Theme, StyleProps>(theme => ({
  root: {
    background: 'green',
    height: isSticky => isSticky ? 'absolute' : 'relative',
  },
}));

export default function Hook() {

  const propsFromSomewhere = {
    isSticky: true
  }

  const classes = useStyles(props);
  return <Button className={classes.root}>Styled with Hook API</Button>;
}
```

```javascript
// Official documentation
const useStyles = makeStyles({
  // style rule
  foo: props => ({
    backgroundColor: props.backgroundColor,
  }),
  bar: {
    // CSS property
    color: props => props.color,
  },
});

```

File: src/client/components/UserPage/AnnouncementModal/index.tsx (hunk 1 above)
Comment (yong-jie) [reply src/client/components/UserPage/AnnouncementModal/index.tsx:233]: i fear that this might defeat the purpose of allowing announcemodal title/message/descriptions to be configurable by env vars in the first place. If we need to update code to change announcement modal behaviour, then we might as well define every aspect of the modal in code

**Review by LoneRifle — APPROVED** [review]
